<?xml version="1.0" standalone="yes" ?>

<!DOCTYPE transcription [
<!ELEMENT transcription (page, annotation)>
<!ELEMENT page EMPTY>
	<!ATTLIST page filename CDATA #REQUIRED>
	<!ATTLIST page pagination CDATA #IMPLIED>
	<!ATTLIST page signature CDATA #IMPLIED>
	<!ATTLIST page reader CDATA #REQUIRED>
	
<!ELEMENT annotation (marginalia*, underline*, symbol*, mark*)>	
	<!ELEMENT marginalia (language*, translation?)>
	<!ATTLIST marginalia hand (English_secretary|Italian) #REQUIRED>
	<!ATTLIST marginalia date CDATA #IMPLIED>
	<!ATTLIST marginalia other_reader CDATA #IMPLIED>
	<!ATTLIST marginalia topic (Law|Astronomy|Warfare|Rhetoric) #IMPLIED> 
	<!ATTLIST marginalia anchor_text CDATA #IMPLIED>
	 	<!ELEMENT language (position*)>
			<!ATTLIST language ident (EN|EL|FR|IT|LA|ES) #REQUIRED> 
				<!ELEMENT position (marginalia_text*, person*, book*, location*, X-ref*, emphasis*)>
					<!ATTLIST position place (head|tail|left_margin|right_margin|intext) #REQUIRED>
					<!ATTLIST position book_orientation	(0|90|180|270) #REQUIRED>
						<!ELEMENT marginalia_text (#PCDATA)>
						<!ELEMENT person EMPTY>
							<!ATTLIST person name CDATA #REQUIRED>
						<!ELEMENT book EMPTY>
							<!ATTLIST book title CDATA #REQUIRED>
						<!ELEMENT location EMPTY>
							<!ATTLIST location name CDATA #REQUIRED>
						<!ELEMENT X-ref EMPTY>
							<!ATTLIST X-ref person CDATA #REQUIRED>
							<!ATTLIST X-ref book_title CDATA #REQUIRED>
						<!ELEMENT emphasis EMPTY> 
							<!ATTLIST emphasis method (chalk|pen) #REQUIRED>
							<!ATTLIST emphasis text CDATA #IMPLIED>
		<!ELEMENT translation (#PCDATA)>
	<!ELEMENT underline EMPTY>
		<!ATTLIST underline method (chalk|pen) #REQUIRED>
		<!ATTLIST underline type (straight|curved) #REQUIRED>
		<!ATTLIST underline language (EN|EL|FR|IT|LA|ES) #IMPLIED>
		<!ATTLIST underline text CDATA #IMPLIED> 
	<!ELEMENT symbol EMPTY>
		<!ATTLIST symbol name (Asterisk|Bisected_circle|Crown|Crescent|JC|HT|LL|Mars|Mercury|Opposite_planets|Square|SS|Sun) #REQUIRED>
		<!ATTLIST symbol place (head|tail|left_margin|right_margin|intext) #REQUIRED>
		<!ATTLIST symbol language (EN|EL|FR|IT|LA|ES) #IMPLIED>
		<!ATTLIST symbol text CDATA #IMPLIED>
	<!ELEMENT mark EMPTY>
		<!ATTLIST mark name	(apostrophe|box|bracket|circumflex|comma|dash|dot|equal_sign|hash|horizontal_bar|plus_sign|quotation_mark|semicolon|straight_quotation_mark|tilde|triple_dash|vertical_bar|X_sign) #REQUIRED>
		<!ATTLIST mark method (chalk|pen) #REQUIRED>
		<!ATTLIST mark place (head|tail|left_margin|right_margin|intext) #REQUIRED>
		<!ATTLIST mark language (EN|EL|FR|IT|LA|ES) #IMPLIED>
		<!ATTLIST mark text CDATA #IMPLIED>
			
<!ENTITY agrave "à">
<!ENTITY aacute "á">
<!ENTITY atiled "ã">
<!ENTITY eacute "é">
<!ENTITY egrave "è">
<!ENTITY ecirc "ê">
<!ENTITY ograve "ò">
<!ENTITY ocirc "Ô">
<!ENTITY euml "ë">
<!ENTITY igrave "ì">
<!ENTITY ugrave "ù">
]
>

<transcription>
    <page filename="Domenichi_014right" pagination="339" reader="Harvey"/>
    <annotation>
        
        <!-- Marginalia -->
        <marginalia hand="Italian">
            <language ident="LA">
                <position place="head" book_orientation="0">
                    <marginalia_text>
                      Vita Eudromi.
                    </marginalia_text>
                	<person name="Eudromus"/>
                </position>
            </language>
        </marginalia>
    	<marginalia hand="Italian">
    		<language ident="LA">
    			<position place="head" book_orientation="0">
    				<marginalia_text>
    					( polytechnia, et polypraxia.
    				</marginalia_text>
    			</position>
    		</language>
    	</marginalia>
    	<marginalia hand="Italian">
    		<language ident="IT">
    			<position place="tail" book_orientation="0">
    				<marginalia_text>
    				( solo Cancelliere, politico. )	
    				</marginalia_text>
    			</position>
    		</language>
    	</marginalia>
    	<marginalia hand="Italian">
    		<language ident="LA">
    			<position place="tail" book_orientation="0">
    				<marginalia_text>
    					&ocirc; quot minuta studia? heu egregia quam pauca?
    				</marginalia_text>
    			</position>
    		</language>
    	</marginalia>
    	<marginalia hand="Italian">
    		<language ident="LA">
    			<position place="left_margin" book_orientation="90">
    				<marginalia_text>
    					Spiritus intus alit: spiritus intus agit. Vnicismus ab Vnico:
    					non &agrave; multis.		<!-- Chalk mark looks like it wore off from the facing page. --> <!--JG: I agree!-->
    				</marginalia_text>
    			</position>
    		</language>
    	</marginalia>
    	<marginalia hand="Italian">
    		<language ident="LA">
    			<position place="right_margin" book_orientation="90">
    				<marginalia_text>
    					Discere Summa; exquirere Summa; retexere Summa;
    					Summa docere; Sequi, extendere, vita mea est. }
    				</marginalia_text>
    			</position>
    		</language>
    	</marginalia>
        
        <!-- Underlines -->
        
    	<underline method="pen" type="straight" language="IT" text="sia un Re molto ricco"/>
    	<underline method="pen" type="straight" language="IT" text="doue spender&ograve; io"/>
    	<underline method="pen" type="straight" language="IT" text="stati donati"/>
    	<underline method="pen" type="straight" language="IT" text="donargli altrui"/>
    	<underline method="pen" type="straight" language="IT" text="gli amici miei, i quali"/>
    	<underline method="pen" type="straight" language="IT" text="fatto seruigio"/>
    	<underline method="pen" type="straight" language="IT" text="loro obligato"/>
    	<underline method="pen" type="straight" language="IT" text="prima che"/>
    	<underline method="pen" type="straight" language="IT" text="questo thesoro"/>
    	<underline method="pen" type="straight" language="IT" text="trassero molti"/>
    	<underline method="pen" type="straight" language="IT" text="gli beeua con gli occhi"/> <!--JG: 'uno' is underlined as well-->
    	<underline method="pen" type="straight" language="IT" text="non racconti tu quel"/>
    	<underline method="pen" type="straight" language="IT" text="in seruigio mio"/>
    	<underline method="pen" type="straight" language="IT" text="pasciuto i Falcino del Re"/>
    	<underline method="pen" type="straight" language="IT" text="un'altro diceua"/>
    	<underline method="pen" type="straight" language="IT" text="quante piu parole"/>
    	<underline method="pen" type="straight" language="IT" text="magnificaua il suo ufficio"/>
    	<underline method="pen" type="straight" language="IT" text="qualche bugia"/>
    	<underline method="pen" type="straight" language="IT" text="lodaua il parlare di ciascuno"/>
    	<underline method="pen" type="straight" language="IT" text="Questa risolutione"/>
    	<underline method="pen" type="straight" language="IT" text="prolungata lungo"/>
    	<underline method="pen" type="straight" language="IT" text="per tormentargli piu"/>
    	<underline method="pen" type="straight" language="IT" text="tutti con la speranza"/>
    	<underline method="pen" type="straight" language="IT" text="con la paura"/>
    	<underline method="pen" type="straight" language="IT" text="primo Ca[n]celliere"/>
    	<underline method="pen" type="straight" language="IT" text="il Re"/>
    	<underline method="pen" type="straight" language="IT" text="Costui piu sauio"/>
    	<underline method="pen" type="straight" language="IT" text="sauio de gli"/> <!--JG: I'd join this with the previous underline tag-->
    	<underline method="pen" type="straight" language="IT" text="non predicaua gli uffici suoi"/>
    	<underline method="pen" type="straight" language="IT" text="spettatore della comedia"/>
    	<underline method="pen" type="straight" language="IT" text="il mio Cancelliere"/>
    	<underline method="pen" type="straight" language="IT" text="non domanda cosa"/>
    	<underline method="pen" type="straight" language="IT" text="ne predica gli uffici suoi"/>
    	<underline method="pen" type="straight" language="IT" text="dalla cortesia"/>
    	<underline method="pen" type="straight" language="IT" text="assai"/>
    	<underline method="pen" type="straight" language="IT" text="piu di quel, che io meritaua"/>
    	<underline method="pen" type="straight" language="IT" text="non come io possa rispondere"/>
    	<underline method="pen" type="straight" language="IT" text="alla liberalit&agrave; sua"/>
    	<underline method="pen" type="straight" language="IT" text="uoglia chiedere cosa alcuna"/>
    	<underline method="pen" type="straight" language="IT" text="tu solo fra tutti non hai"/>
    	<underline method="pen" type="straight" language="IT" text="uostra cortesia, Sire"/>
    	<underline method="pen" type="straight" language="IT" text="che io non n'habbia bisogno"/>
    
        
        <!-- Symbols: Asterisk|Bisected_circle|Crown|Crescent|JC|HT|LL|Mars|Mercury|Opposite_planets|Square|SS|Sun -->
        
        <symbol name="SS" place="right_margin"/>
    	<symbol name="JC" place="right_margin"/>
        
        <!-- Marks: apostrophe|box|bracket|circumflex|comma|dash|dot|equal_sign|hash|horizontal_bar|plus_sign|quotation_mark|semicolon|tilde|triple_dash|vertical_bar|X_sign -->
    	
    	<mark name="quotation_mark" method="pen" place="head"/>
    	
    	<!-- Right margin -->
    	<mark name="plus_sign" method="pen" place="right_margin"/> <!-- Questi mi so- -->
    	<mark name="dash" method="pen" place="right_margin"/> <!-- que -->
    	<mark name="dash" method="pen" place="right_margin"/> <!-- uer -->
    	<mark name="dash" method="pen" place="right_margin"/> <!-- fat -->
    	<mark name="dash" method="pen" place="right_margin"/> <!-- tem -->
    	<mark name="dash" method="pen" place="right_margin"/> <!-- ciascu -->
    	<mark name="dash" method="pen" place="right_margin"/> <!-- uffi -->
    	<mark name="quotation_mark" method="pen" place="right_margin"/> <!-- tutti -->
    	
    	<!-- Left margin -->
    	<mark name="plus_sign" method="pen" place="left_margin"/> <!-- no stati -->
    	<mark name="equal_sign" method="pen" place="left_margin"/> <!-- son hora -->
    	<mark name="straight_quotation_mark" method="pen" place="left_margin"/> <!-- amoreuolmente -->
    	<mark name="bracket" method="pen" place="left_margin"/> <!-- sta... paura -->
    	<mark name="plus_sign" method="pen" place="left_margin"/> <!-- uio de gli -->
    	<mark name="plus_sign" method="pen" place="left_margin"/> <!-- to; che -->
    	<mark name="bracket" method="pen" place="left_margin"/> <!-- il Ca[n]celliere... que il Re -->
    	<mark name="bracket" method="pen" place="left_margin"/> <!-- denari? ... ha fatto -->
    
    	<!-- Intext -->
    	<mark name="dot" method="pen" place="intext"/> <!-- occhi, riuolto -->
    	<mark name="vertical_bar" method="pen" place="intext"/> <!-- spesa: un'altro -->
    	<mark name="vertical_bar" method="pen" place="intext"/> <!-- cosa: & -->
    	<mark name="straight_quotation_mark" method="pen" place="intext"/> <!-- qualche bugia -->
    	<mark name="vertical_bar" method="pen" place="intext"/> <!-- bugia. Il Re -->
    	<mark name="straight_quotation_mark" method="pen" place="intext"/> <!-- lodaua -->
    	<mark name="plus_sign" method="pen" place="intext"/> <!-- primo Ca[n]celliere -->
    	<mark name="plus_sign" method="pen" place="intext"/> <!-- piu sa -->
    	<mark name="straight_quotation_mark" method="pen" place="intext"/> <!-- non predicaua-->
    	<mark name="plus_sign" method="pen" place="intext"/> <!-- comedia -->
    	<mark name="plus_sign" method="pen" place="intext"/> <!-- io meritaua -->
    	<mark name="plus_sign" method="pen" place="intext"/> <!-- tu solo -->
    	
    	<mark name="plus_sign" method="pen" place="tail"/>

    </annotation>
</transcription>