<?xml version="1.0" standalone="yes" ?>

<!DOCTYPE transcription [
<!ELEMENT transcription (page, annotation)>
<!ELEMENT page EMPTY>
	<!ATTLIST page filename CDATA #REQUIRED>
	<!ATTLIST page pagination CDATA #IMPLIED>
	<!ATTLIST page signature CDATA #IMPLIED>
	<!ATTLIST page reader CDATA #REQUIRED>
	
<!ELEMENT annotation (marginalia*, underline*, symbol*, mark*)>	
	<!ELEMENT marginalia (language*, translation?)>
	<!ATTLIST marginalia hand (English_secretary|Italian) #REQUIRED>
	<!ATTLIST marginalia date CDATA #IMPLIED>
	<!ATTLIST marginalia other_reader CDATA #IMPLIED>
	<!ATTLIST marginalia topic (Law|Astronomy|Warfare|Rhetoric) #IMPLIED> 
	<!ATTLIST marginalia anchor_text CDATA #IMPLIED>
	 	<!ELEMENT language (position*)>
			<!ATTLIST language ident (EN|EL|FR|IT|LA|ES) #REQUIRED> 
				<!ELEMENT position (marginalia_text*, person*, book*, location*, X-ref*, emphasis*)>
					<!ATTLIST position place (head|tail|left_margin|right_margin|intext) #REQUIRED>
					<!ATTLIST position book_orientation	(0|90|180|270) #REQUIRED>
						<!ELEMENT marginalia_text (#PCDATA)>
						<!ELEMENT person EMPTY>
							<!ATTLIST person name CDATA #REQUIRED>
						<!ELEMENT book EMPTY>
							<!ATTLIST book title CDATA #REQUIRED>
						<!ELEMENT location EMPTY>
							<!ATTLIST location name CDATA #REQUIRED>
						<!ELEMENT X-ref EMPTY>
							<!ATTLIST X-ref person CDATA #REQUIRED>
							<!ATTLIST X-ref book_title CDATA #REQUIRED>
						<!ELEMENT emphasis EMPTY> 
							<!ATTLIST emphasis method (chalk|pen) #REQUIRED>
							<!ATTLIST emphasis text CDATA #IMPLIED>
		<!ELEMENT translation (#PCDATA)>
	<!ELEMENT underline EMPTY>
		<!ATTLIST underline method (chalk|pen) #REQUIRED>
		<!ATTLIST underline type (straight|curved) #REQUIRED>
		<!ATTLIST underline language (EN|EL|FR|IT|LA|ES) #IMPLIED>
		<!ATTLIST underline text CDATA #IMPLIED> 
	<!ELEMENT symbol EMPTY>
		<!ATTLIST symbol name (Asterisk|Bisected_circle|Crown|Crescent|JC|HT|LL|Mars|Mercury|Opposite_planets|Square|SS|Sun) #REQUIRED>
		<!ATTLIST symbol place (head|tail|left_margin|right_margin|intext) #REQUIRED>
		<!ATTLIST symbol language (EN|EL|FR|IT|LA|ES) #IMPLIED>
		<!ATTLIST symbol text CDATA #IMPLIED>
	<!ELEMENT mark EMPTY>
		<!ATTLIST mark name	(apostrophe|box|bracket|circumflex|comma|dash|dot|equal_sign|hash|horizontal_bar|plus_sign|quotation_mark|semicolon|straight_quotation_mark|tilde|triple_dash|vertical_bar|X_sign) #REQUIRED>
		<!ATTLIST mark method (chalk|pen) #REQUIRED>
		<!ATTLIST mark place (head|tail|left_margin|right_margin|intext) #REQUIRED>
		<!ATTLIST mark language (EN|EL|FR|IT|LA|ES) #IMPLIED>
		<!ATTLIST mark text CDATA #IMPLIED>
			
<!ENTITY agrave "à">
<!ENTITY aacute "á">
<!ENTITY atiled "ã">
<!ENTITY eacute "é">
<!ENTITY egrave "è">
<!ENTITY ecirc "ê">
<!ENTITY ograve "ò">
<!ENTITY ocirc "Ô">
<!ENTITY euml "ë">
<!ENTITY igrave "ì">
<!ENTITY ugrave "ù">
]
>

<transcription>
    <page filename="Domenichi_013left" pagination="336" reader="Harvey"/>
    <annotation>
        
        <!-- Marginalia -->
        <marginalia hand="Italian">
            <language ident="LA">
                <position place="head" book_orientation="0">
                    <marginalia_text>
                      Vita Astrophili.
                    </marginalia_text>
                	<person name="Astrophil"/>
                </position>
            </language>
        </marginalia>
    	<marginalia hand="Italian">
    		<language ident="LA">
    			<position place="left_margin" book_orientation="0">
    				<marginalia_text>
    					Elixir vitae, Industria
    				</marginalia_text>
    			</position>
    		</language>
    	</marginalia>
    	<marginalia hand="Italian">
    		<language ident="IT">
    			<position place="intext" book_orientation="0">
    				<marginalia_text>
    					Problema ridicolo.
    				</marginalia_text>
    			</position>
    		</language>
    	</marginalia>
    	<marginalia hand="Italian">
    		<language ident="EN">
    			<position place="intext" book_orientation="0">
    				<marginalia_text>
    					Euerie dat better, &amp; better.
    				</marginalia_text>
    				<emphasis method="pen" text="Euerie"/>
    				<emphasis method="pen" text="better, &amp; better"/>
    			</position>
    		</language>
    	</marginalia>
    	<marginalia hand="Italian">
    		<language ident="IT">
    			<position place="tail" book_orientation="0">
    				<marginalia_text>
    					{ Pontano, nato a piaceuolezze. )
    				</marginalia_text>
    				<person name="Giovanni Pontano"/>
    			</position>
    		</language>
    		<language ident="LA">
    			<position place="tail" book_orientation="0">
    				<marginalia_text>
    					philosophus, philautus.
    				</marginalia_text>
    			</position>
    		</language>
    	</marginalia>
    	<marginalia hand="Italian">
    		<language ident="LA">
    			<position place="left_margin" book_orientation="90">
    				<marginalia_text>
    					[mih]i vita est, essentia quinta valoris;
    					s, virtus, praxis multiplicata potens. }
    				</marginalia_text>
    			</position>
    		</language>
    	</marginalia>
    	<marginalia hand="Italian">
    		<language ident="EN">
    			<position place="right_margin" book_orientation="90">
    				<marginalia_text>
    					Manie [bigg] [??] are little worth: &amp; manie little men of great valour:
    					<!-- There appears to be more text beneath, however the page is bent and illegible. -->
    				</marginalia_text>
    			</position>
    		</language>
    	</marginalia>
    	<marginalia hand="Italian">
    		<language ident="LA">
    			<position place="right_margin" book_orientation="270">
    				<marginalia_text>
    					tota in toto. res enim cum
    				</marginalia_text>
    			</position>
    			<position place="intext" book_orientation="270">
    				<marginalia_text>
    					Euschemosyne,    <!-- These do not seem to be names of people, as the first is Greek for "decorum," however I can't figure out "Fronismo," although the Greek root seems easy enough to guess. -->
    					et
    					Fronismo.
    				</marginalia_text>
    			</position>
    		</language>
    	</marginalia>
        
        <!-- Underlines -->
        
        <underline method="pen" type="straight" language="IT" text="tuttauia messere"/>
    	<underline method="pen" type="straight" language="IT" text="quella riuerentia"/>
    	<underline method="pen" type="straight" language="IT" text="messa"/>
    	<underline method="pen" type="straight" language="IT" text="canto rozo"/>
    	<underline method="pen" type="straight" language="IT" text="uillanesco"/>
    	<underline method="pen" type="straight" language="IT" text="altra donna"/>
    	<underline method="pen" type="straight" language="IT" text="nudo all'altare"/>
    	<underline method="pen" type="straight" language="IT" text="esser uestito"/>
    	<underline method="pen" type="straight" language="IT" text="la terza"/>
    	<underline method="pen" type="straight" language="IT" text="egli era morto"/>
    	<underline method="pen" type="straight" language="IT" text="sulla bara"/>
    	<underline method="pen" type="straight" language="IT" text="i suoi uicini"/>
    	<underline method="pen" type="straight" language="IT" text="frate"/>
    	<underline method="pen" type="straight" language="IT" text="ignudo"/>
    	<underline method="pen" type="straight" language="IT" text="mi riderei molto di"/>
    	<underline method="pen" type="straight" language="IT" text="queste pazzie de' miei"/>
    	<underline method="pen" type="straight" language="IT" text="queste tre donne habbia uinta la"/>
    	<underline method="pen" type="straight" language="IT" text="ingegnose quistioni"/>
    	<underline method="pen" type="straight" language="IT" text="le balie"/>
    	<underline method="pen" type="straight" language="IT" text="cantar delle"/>
    	<underline method="pen" type="straight" language="IT" text="il Pontano"/>
    	<underline method="pen" type="straight" language="IT" text="mirabilmente"/>
    	<underline method="pen" type="straight" language="IT" text="piaceuole in esprimere"/>
    	<underline method="pen" type="straight" language="IT" text="d'eloquentia, &amp; di dottrina con"/>
    	<underline method="pen" type="straight" language="IT" text="egli sia nato solamente"/>
    	<underline method="pen" type="straight" language="IT" text="a"/>
    	<underline method="pen" type="straight" language="IT" text="piaceuolezze"/>
    	
    
        
        <!-- Symbols: Asterisk|Bisected_circle|Crown|Crescent|JC|HT|LL|Mars|Mercury|Opposite_planets|Square|SS|Sun -->
        
        <symbol name="Sun" place="head"/>
    	<symbol name="Sun" place="head"/>
    	<symbol name="JC" place="intext"/>
    	<symbol name="SS" place="left_margin"/>
        
        <!-- Marks: apostrophe|box|bracket|circumflex|comma|dash|dot|equal_sign|hash|horizontal_bar|plus_sign|quotation_mark|semicolon|tilde|triple_dash|vertical_bar|X_sign -->
    	
    	<!-- Right margin -->
    	<mark name="dash" method="pen" place="right_margin"/> <!-- co -->
    	<mark name="dash" method="pen" place="right_margin"/> <!-- don -->
    	<mark name="dash" method="pen" place="right_margin"/> <!-- mira -->
    	<mark name="dash" method="pen" place="right_margin"/> <!-- pia -->
    	<mark name="dash" method="pen" place="right_margin"/> <!-- caminan -->
    	
    	<!-- Left margin -->
    	<mark name="quotation_mark" method="pen" place="left_margin"/> <!-- bilmente -->
    	<mark name="quotation_mark" method="pen" place="left_margin"/> <!-- ceuolezze -->
    
    	<!-- Intext -->
    	<mark name="vertical_bar" method="pen" place="intext"/> <!-- uillanesco; l'altra -->
    	<mark name="vertical_bar" method="pen" place="intext"/> <!-- uestito. Ma la terza -->
    	<mark name="dot" method="pen" place="intext"/> <!-- frate, & l'altro -->
    	<mark name="dot" method="pen" place="intext"/> <!-- l'offerta, disse -->
    	<mark name="plus_sign" method="pen" place="intext" language="IT" text="tre donne"/>
    	<mark name="quotation_mark" method="pen" place="intext"/> <!-- quistioni.] -->
    	<mark name="quotation_mark" method="pen" place="intext"/> <!-- Sogliono -->
    	<mark name="plus_sign" method="pen" place="intext" language="IT" text="Pontano"/>
    	<mark name="equal_sign" method="pen" place="intext" /> <!-- fu mira -->
    	<mark name="plus_sign" method="pen" place="intext" language="IT" text="nato"/>
    	<mark name="equal_sign" method="pen" place="intext" /> <!-- solamente -->
    	
    	<mark name="vertical_bar" method="chalk" place="intext"/> <!-- Middle of page to the left -->
    	<mark name="vertical_bar" method="chalk" place="intext"/> <!-- Bottom of page to the left -->

    </annotation>
</transcription>