<?xml version="1.0" standalone="yes" ?>

<!DOCTYPE transcription [
<!ELEMENT transcription (page, annotation)>
<!ELEMENT page EMPTY>
	<!ATTLIST page filename CDATA #REQUIRED>
	<!ATTLIST page pagination CDATA #IMPLIED>
	<!ATTLIST page signature CDATA #IMPLIED>
	<!ATTLIST page reader CDATA #REQUIRED>
	
<!ELEMENT annotation (marginalia*, underline*, symbol*, mark*)>	
	<!ELEMENT marginalia (language*, translation?)>
	<!ATTLIST marginalia hand (English_secretary|Italian) #REQUIRED>
	<!ATTLIST marginalia date CDATA #IMPLIED>
	<!ATTLIST marginalia other_reader CDATA #IMPLIED>
	<!ATTLIST marginalia topic (Law|Astronomy|Warfare|Rhetoric) #IMPLIED> 
	<!ATTLIST marginalia anchor_text CDATA #IMPLIED>
	 	<!ELEMENT language (position*)>
			<!ATTLIST language ident (EN|EL|FR|IT|LA|ES) #REQUIRED> 
				<!ELEMENT position (marginalia_text*, person*, book*, location*, X-ref*, emphasis*)>
					<!ATTLIST position place (head|tail|left_margin|right_margin|intext) #REQUIRED>
					<!ATTLIST position book_orientation	(0|90|180|270) #REQUIRED>
						<!ELEMENT marginalia_text (#PCDATA)>
						<!ELEMENT person EMPTY>
							<!ATTLIST person name CDATA #REQUIRED>
						<!ELEMENT book EMPTY>
							<!ATTLIST book title CDATA #REQUIRED>
						<!ELEMENT location EMPTY>
							<!ATTLIST location name CDATA #REQUIRED>
						<!ELEMENT X-ref EMPTY>
							<!ATTLIST X-ref person CDATA #REQUIRED>
							<!ATTLIST X-ref book_title CDATA #REQUIRED>
						<!ELEMENT emphasis EMPTY> 
							<!ATTLIST emphasis method (chalk|pen) #REQUIRED>
							<!ATTLIST emphasis text CDATA #IMPLIED>
		<!ELEMENT translation (#PCDATA)>
	<!ELEMENT underline EMPTY>
		<!ATTLIST underline method (chalk|pen) #REQUIRED>
		<!ATTLIST underline type (straight|curved) #REQUIRED>
		<!ATTLIST underline language (EN|EL|FR|IT|LA|ES) #IMPLIED>
		<!ATTLIST underline text CDATA #IMPLIED> 
	<!ELEMENT symbol EMPTY>
		<!ATTLIST symbol name (Asterisk|Bisected_circle|Crown|Crescent|JC|HT|LL|Mars|Mercury|Opposite_planets|Square|SS|Sun) #REQUIRED>
		<!ATTLIST symbol place (head|tail|left_margin|right_margin|intext) #REQUIRED>
		<!ATTLIST symbol language (EN|EL|FR|IT|LA|ES) #IMPLIED>
		<!ATTLIST symbol text CDATA #IMPLIED>
	<!ELEMENT mark EMPTY>
		<!ATTLIST mark name	(apostrophe|box|bracket|circumflex|comma|dash|dot|equal_sign|hash|horizontal_bar|plus_sign|quotation_mark|semicolon|straight_quotation_mark|tilde|triple_dash|vertical_bar|X_sign) #REQUIRED>
		<!ATTLIST mark method (chalk|pen) #REQUIRED>
		<!ATTLIST mark place (head|tail|left_margin|right_margin|intext) #REQUIRED>
		<!ATTLIST mark language (EN|EL|FR|IT|LA|ES) #IMPLIED>
		<!ATTLIST mark text CDATA #IMPLIED>
			
<!ENTITY agrave "à">
<!ENTITY aacute "á">
<!ENTITY atiled "ã">
<!ENTITY eacute "é">
<!ENTITY egrave "è">
<!ENTITY ecirc "ê">
<!ENTITY ograve "ò">
<!ENTITY ocirc "Ô">
<!ENTITY euml "ë">
<!ENTITY igrave "ì">
<!ENTITY ugrave "ù">
]
>

<transcription>
    <page filename="Domenichi_009right" pagination="329" reader="Harvey"/>
    <annotation>
        
        <!-- Marginalia -->
        <marginalia hand="Italian">
            <language ident="LA">
                <position place="head" book_orientation="0">
                    <marginalia_text>
                      Singula ex arte Decori.
                    </marginalia_text>
                </position>
            </language>
        </marginalia>
    	<marginalia hand="Italian">
    		<language ident="EN">
    			<position place="left_margin" book_orientation="90">
    				<marginalia_text>
    					Pronunciation most pliant to the matter vttered: &amp; the liueliest
    					interpreter, that euer explaned anie speach bic apt vtterance.
    				</marginalia_text>
    				<emphasis method="chalk"/>
    			</position>
    		</language>
    	</marginalia>
    	<marginalia hand="Italian">
    		<language ident="LA">
    			<position place="intext" book_orientation="0">
    				<marginalia_text>
    					su[pra]
    				</marginalia_text>
    			</position>
    		</language>
    		<language ident="IT">
    			<position place="intext" book_orientation="0">
    				<marginalia_text>
    					/ 160. discretamente.
    				</marginalia_text>
    			</position>
    		</language>
    	</marginalia>
    	<marginalia hand="Italian">
    		<language ident="EN">
    			<position place="intext" book_orientation="0">
    				<marginalia_text>
    					) no more scribling: but enjoy he excellent, &amp; diuine notes,
    				</marginalia_text>
    				<emphasis method="chalk"/>
    			</position>
    			<position place="right_margin" book_orientation="0">
    				<marginalia_text>
    					which you haue allreddi written.
    				</marginalia_text>
    			</position>
    		</language>
    	</marginalia>
    	<marginalia hand="Italian">
    		<language ident="LA">
    			<position place="tail" book_orientation="0">
    				<marginalia_text>
    					Quid pro quo,
    				</marginalia_text>
    			</position>
    		</language>
    		<language ident="EN">
    			<position place="tail" book_orientation="0">
    				<marginalia_text>
    					will supplie anie defects, anie
    					sooner doon, then saide, a sure course.
    				</marginalia_text>
    			</position>
    		</language>
    	</marginalia>
    	<marginalia hand="Italian">
    		<language ident="EN">
    			<position place="right_margin" book_orientation="270">
    				<marginalia_text>
    					His voice, a viue commentarie to whatsoeuer he speaketh,
    					or readeth. A speaking Glasse: or talking picture.
    				</marginalia_text>
    				<emphasis method="chalk"/>
    			</position>
    		</language>
    	</marginalia>
        
        <!-- Underlines -->
        
    	<underline method="pen" type="straight" language="IT" text="Cardinal Rucellai che era"/>
    	<underline method="pen" type="straight" language="IT" text="che l'aiutasse"/>
    	<underline method="pen" type="straight" language="IT" text="dolendosi del cancelliere, con dire"/>
    	<underline method="pen" type="straight" language="IT" text="Il cancelliere, inform&ograve;"/>
    	<underline method="pen" type="straight" language="IT" text="cancelliere, dicendogli"/>
    	<underline method="pen" type="straight" language="IT" text="una carta di uillania"/>
    	<underline method="pen" type="straight" language="IT" text="cancelliere"/>
    	<underline method="pen" type="straight" language="IT" text="non rispose altro"/>
    	<underline method="pen" type="straight" language="IT" text="non"/>
    	<underline method="pen" type="straight" language="IT" text="due"/>
    	<underline method="pen" type="straight" language="IT" text="andosi"/>
    	<underline method="pen" type="straight" language="IT" text="Non si guadagna nulla"/>
    	<underline method="pen" type="straight" language="IT" text="trauagliarsi co' pazzi"/>
    	<underline method="pen" type="straight" language="IT" text="citt&agrave; di Lamagna"/>
    	<underline method="pen" type="straight" language="IT" text="un galant'huomo"/>
    	<underline method="pen" type="straight" language="IT" text="per Borgomastro"/>
    	<underline method="pen" type="straight" language="IT" text="maggior puttaniere"/>
    	<underline method="pen" type="straight" language="IT" text="in quell'ufficio"/>
    	<underline method="pen" type="straight" language="IT" text="quel che il popolo diceua del Borgomastro"/>
    	<underline method="pen" type="straight" language="IT" text="quel che si facciano, o dicano gli altri"/>
    	<underline method="pen" type="straight" language="IT" text="lauorare nel campo"/>
    	<underline method="pen" type="straight" language="IT" text="priuato, amo la pace"/>
    	<underline method="pen" type="straight" language="IT" text="gli huomini saui di questo mondo"/>
    	<underline method="pen" type="straight" language="IT" text="piu uolte ingannato"/>
    	<underline method="pen" type="straight" language="IT" text="a uendere il cacio"/>
    	<underline method="pen" type="straight" language="IT" text="il Borgomastro"/>
    	<underline method="pen" type="straight" language="IT" text="e' non &egrave; molto"/>
    	<underline method="pen" type="straight" language="IT" text="da mia madre"/>
    	<underline method="pen" type="straight" language="IT" text="era un gran ruffiano"/>
    	<underline method="pen" type="straight" language="IT" text="uituperato una mia parente"/>
    	<underline method="pen" type="straight" language="IT" text="quei due barri"/>
    	<underline method="pen" type="straight" language="IT" text="non &egrave; molto che"/>
    	<underline method="pen" type="straight" language="IT" text="furono affogati"/>
    	<underline method="pen" type="straight" language="IT" text="le truffe, che"/>
    	<underline method="pen" type="straight" language="IT" text="il Borgomastro se n'and&ograve;"/>
     
        <!-- Symbols: Asterisk|Bisected_circle|Crown|Crescent|JC|HT|LL|Mars|Mercury|Opposite_planets|Square|SS|Sun -->
        
        <symbol name="Sun" place="head"/>
        
        <!-- Marks: apostrophe|box|bracket|circumflex|comma|dash|dot|equal_sign|hash|plus_sign|quotation_mark|semicolon|tilde|triple_dash|vertical_bar|X_sign -->
    	
    	<!-- Right margin -->
    	<mark name="dash" method="pen" place="right_margin"/> <!-- ca -->
    	<mark name="plus_sign" method="pen" place="right_margin"/> <!-- trauagliarsi -->
    	<mark name="quotation_mark" method="pen" place="right_margin"/> <!-- pae -->
    	<mark name="dash" method="pen" place="right_margin"/> <!-- doman -->
    	<mark name="quotation_mark" method="pen" place="right_margin"/> <!-- era un gran -->
    	<mark name="dash" method="pen" place="right_margin"/> <!-- Et co -->
    	
    	<!-- Left margin -->
    	<mark name="bracket" method="pen" place="left_margin"/> <!-- se al ... co' pazzi. -->
    	<mark name="vertical_bar" method="pen" place="left_margin"/>
    	
    	<!-- Intext punctuation -->        
    	<mark name="dot" method="pen" place="intext"/> <!-- cancelliere, con -->
    	<mark name="straight_quotation_mark" method="pen" place="intext"/>
    	<mark name="straight_quotation_mark" method="pen" place="intext" language="IT" text="pazzi"/>
    	<mark name="plus_sign" method="pen" place="intext"/> <!-- co' pazzi.] -->
    	<mark name="plus_sign" method="pen" place="intext"/> <!-- per Borgomastro -->
    	<mark name="dot" method="pen" place="intext"/> <!-- Borgomastro, il -->
    	<mark name="plus_sign" method="pen" place="intext"/> <!-- gli altri -->
    	<mark name="dot" method="pen" place="intext"/> <!-- pace, non -->
    	<mark name="plus_sign" method="pen" place="intext" language="IT" text="saui"/>
    	<mark name="vertical_bar" method="pen" place="intext"/> <!-- il cacio. | Disse -->
    	<mark name="vertical_bar" method="pen" place="intext"/> <!-- piu persone. | Et co -->
    	
    	<!-- Tail -->
    	<mark name="dot" method="pen" place="tail"/> <!-- After "teso" -->
        
    </annotation>
</transcription>