<?xml version="1.0" standalone="yes" ?>

<!DOCTYPE transcription [
<!ELEMENT transcription (page, annotation)>
<!ELEMENT page EMPTY>
	<!ATTLIST page filename CDATA #REQUIRED>
	<!ATTLIST page pagination CDATA #IMPLIED>
	<!ATTLIST page signature CDATA #IMPLIED>
	<!ATTLIST page reader CDATA #REQUIRED>

<!ELEMENT annotation (marginalia*, underline*, symbol*, mark*)>	
	<!ELEMENT marginalia (language*, translation?)>
	<!ATTLIST marginalia hand (English_secretary|Italian) #REQUIRED>
	<!ATTLIST marginalia date CDATA #IMPLIED>
	<!ATTLIST marginalia other_reader CDATA #IMPLIED>
	<!ATTLIST marginalia topic (Law|Astronomy|Warfare|Rhetoric) #IMPLIED> 
	<!ATTLIST marginalia anchor_text CDATA #IMPLIED>
	 	<!ELEMENT language (position*)>
			<!ATTLIST language ident (EN|EL|FR|IT|LA|ES) #REQUIRED> 
				<!ELEMENT position (marginalia_text*, person*, book*, location*, X-ref*, emphasis*)>
					<!ATTLIST position place (head|tail|left_margin|right_margin|intext) #REQUIRED>
					<!ATTLIST position book_orientation	(0|90|180|270) #REQUIRED>
						<!ELEMENT marginalia_text (#PCDATA)>
						<!ELEMENT person EMPTY>
							<!ATTLIST person name CDATA #REQUIRED>
						<!ELEMENT book EMPTY>
							<!ATTLIST book title CDATA #REQUIRED>
						<!ELEMENT location EMPTY>
							<!ATTLIST location name CDATA #REQUIRED>
						<!ELEMENT X-ref EMPTY>
							<!ATTLIST X-ref person CDATA #REQUIRED>
							<!ATTLIST X-ref book_title CDATA #REQUIRED>
						<!ELEMENT emphasis EMPTY> 
							<!ATTLIST emphasis method (chalk|pen) #REQUIRED>
							<!ATTLIST emphasis text CDATA #IMPLIED>
		<!ELEMENT translation (#PCDATA)>
	<!ELEMENT underline EMPTY>
		<!ATTLIST underline method (chalk|pen) #REQUIRED>
		<!ATTLIST underline type (straight|curved) #REQUIRED>
		<!ATTLIST underline language (EN|EL|FR|IT|LA|ES) #IMPLIED>
		<!ATTLIST underline text CDATA #IMPLIED> 
	<!ELEMENT symbol EMPTY>
		<!ATTLIST symbol name (Asterisk|Bisected_circle|Crown|Crescent|JC|HT|LL|Mars|Mercury|Opposite_planets|Square|SS|Sun) #REQUIRED>
		<!ATTLIST symbol place (head|tail|left_margin|right_margin|intext) #REQUIRED>
		<!ATTLIST symbol language (EN|EL|FR|IT|LA|ES) #IMPLIED>
		<!ATTLIST symbol text CDATA #IMPLIED>
	<!ELEMENT mark EMPTY>
		<!ATTLIST mark name	(apostrophe|box|bracket|circumflex|comma|dash|dot|equal_sign|hash|horizontal_bar|plus_sign|quotation_mark|semicolon|straight_quotation_mark|tilde|triple_dash|vertical_bar|X_sign) #REQUIRED>
		<!ATTLIST mark method (chalk|pen) #REQUIRED>
		<!ATTLIST mark place (head|tail|left_margin|right_margin|intext) #REQUIRED>
		<!ATTLIST mark language (EN|EL|FR|IT|LA|ES) #IMPLIED>
		<!ATTLIST mark text CDATA #IMPLIED>
			
<!ENTITY agrave "à">
<!ENTITY aacute "á">
<!ENTITY atiled "ã">
<!ENTITY egrave "è">
<!ENTITY eacute "é">
<!ENTITY ecirc "ê">
<!ENTITY igrave "ì">
<!ENTITY ograve "ò">
<!ENTITY Ocirc "Ô">
<!ENTITY euml "ë">
]
>

<transcription>
    <page filename="Ha2.003r.tif" pagination="325" reader="Harvey"/>	<!-- ABO 007right -->
    <annotation>
        <!-- Marginalia -->
        <marginalia hand="Italian">
            <language ident="LA">
                <position place="head" book_orientation="0">
                    <marginalia_text>Qui Venerem nescit, nescit mollitiem, teneritatem,
                        lassitudinem, aestus languorum, 
                    </marginalia_text>
                    <person name="Venus"/>
                </position>
            </language>
        </marginalia>
        <marginalia hand="Italian">
            <language ident="LA">
                <position place="right_margin" book_orientation="0">
                    <marginalia_text>
                        frigoris asperitatem, inediam, 
                    </marginalia_text>
                </position>
            </language>
        </marginalia>
       <marginalia hand="Italian">
            <language ident="LA">
                <position place="intext" book_orientation="0">
                    <marginalia_text>
                        sitim, multas lascivorum agritudines, plurima
                    </marginalia_text>
                </position>
            </language>
        </marginalia>
        <marginalia hand="Italian">
            <language ident="LA">
                <position place="right_margin" book_orientation="0">
                    <marginalia_text>a&ecirc;ris, vigiliarum, aliorumq[ue] accidentium incommoda, quae</marginalia_text> 
                </position>
                <position place="intext" book_orientation="0">
                    <marginalia_text>
                        luxuriosis videntur peracerba, et prop&egrave; intolerabilia.
                    </marginalia_text>
                </position>
            </language>
        </marginalia>
        <marginalia hand="Italian">
            <language ident="IT">
                <position place="intext" book_orientation="0">
                    <marginalia_text>
                        ridicolo.)
                    </marginalia_text>
                </position>
            </language>
        </marginalia>
        <marginalia hand="Italian">
            <language ident="LA">
                <position place="right_margin" book_orientation="0">
                    <marginalia_text>
                        Moll[io] dura omnia: |duro durum nihil. Iucundo
                        nihil acerbius: acerbo nihil iucundius.
                    </marginalia_text>
                </position>
            </language>
        </marginalia>
        <marginalia hand="Italian">
            <language ident="EN">
                <position place="intext" book_orientation="0">
                    <marginalia_text>
                        He is the tallest man, that hath the tallest minde, &amp; the highest Witt.                         
                    </marginalia_text>
                </position>
            </language>
        </marginalia>
        <marginalia hand="Italian">
            <language ident="IT">
                <position place="intext" book_orientation="0">
                    <marginalia_text>discretamente.</marginalia_text>
                </position>
            </language>
		</marginalia>
		<marginalia hand="Italian">	
            <language ident="LA">
                <position place="intext" book_orientation="0">
                    <marginalia_text>
                        distinctio civilis plurimi in mundo usus.
                    </marginalia_text>
                </position>
            </language>
        </marginalia>
        <marginalia hand="Italian" anchor_text="Pronto.">
            <language ident="LA">
                <position place="intext" book_orientation="0">
                    <marginalia_text>
                        dextr&egrave;.
                    </marginalia_text>
                </position>
            </language>
        </marginalia>
        <marginalia hand="Italian">
            <language ident="LA">
                <position place="tail" book_orientation="0">
                    <marginalia_text>
                        prose quisq[ue], quarto modo.
                    </marginalia_text>
                </position>
            </language>
        </marginalia>
        <marginalia hand="Italian">
            <language ident="EN">
                <position place="left_margin" book_orientation="90">
                    <marginalia_text>
                       | He is a noble man, that hath a noble minde, &amp; an honorable Witt.
                    </marginalia_text>
                </position>
            </language>
        </marginalia>
        <marginalia hand="Italian">
            <language ident="LA">
                <position place="right_margin" book_orientation="270">
                    <marginalia_text>
                        Quotidie assuescere, summum robusti, agilisq[ue] viri bonum.
                    </marginalia_text>
                </position>
            </language>
        </marginalia>
        <marginalia hand="Italian">
            <language ident="LA">
                <position place="right_margin" book_orientation="0">
                    <marginalia_text>
                        s[upr]a )
                    </marginalia_text>
                </position>
            </language>
        </marginalia>
        <!-- Underlines -->
        <underline method="pen" type="straight" language="IT" text="a piangere"/>
        <underline method="pen" type="straight" language="IT" text="a ridere"/>
        <underline method="pen" type="straight" language="IT" text="buona Christianella"/>
        <underline method="pen" type="straight" language="IT" text="appiccare l'uncino"/>
        <underline method="pen" type="straight" language="IT" text="Non per l'amor di Dio"/>
        <underline method="pen" type="straight" language="IT" text="tu n'hai bisogno."/>
        <underline method="pen" type="straight" language="IT" text="Bartolomeo Paganelli"/>
        <underline method="pen" type="straight" language="IT" text="limosina per amor di Dio."/>
        <underline method="pen" type="straight" language="IT" text="del pouero che chiede"/>
        <underline method="pen" type="straight" language="IT" text="che fa la limosina"/>
        <underline method="pen" type="straight" language="IT" text="stare con"/>
        <underline method="pen" type="straight" language="IT" text="fa fuoco in finestra"/>
        <underline method="pen" type="straight" language="IT" text="ne' camini"/>
        <underline method="pen" type="straight" language="IT" text="usino stufe"/>
        <underline method="pen" type="straight" language="IT" text="molte altre simplicit&agrave;"/>
        <underline method="pen" type="straight" language="IT" text="che ella si butter&agrave;"/>
        <underline method="pen" type="straight" language="IT" text="uolesse fare"/>
        <underline method="pen" type="straight" language="IT" text="oh che"/>
        <underline method="pen" type="straight" language="IT" text="seconda che la butter&agrave;"/>
        <underline method="pen" type="straight" language="IT" text="non sapeua ci&ograve; che hauesse"/>
        <underline method="pen" type="straight" language="IT" text="un Giudeo"/>
        <underline method="pen" type="straight" language="IT" text="haurebbe tocchi"/>
        <underline method="pen" type="straight" language="IT" text="Sabato non &egrave;"/>
        <underline method="pen" type="straight" language="IT" text="denari non ci sono"/>
        <underline method="pen" type="straight" language="IT" text="Pronto."/>
        <underline method="pen" type="straight" language="IT" text="pazzo"/>
        <underline method="pen" type="straight" language="IT" text="cane e'"/>
        <underline method="pen" type="straight" language="IT" text="un bracco, tocc&ograve;"/>
        <underline method="pen" type="straight" language="IT" text="s&ograve; che mazzata"/>
        <underline method="pen" type="straight" language="IT" text="oh tale d&agrave; a quel cane"/>
        
        <!-- Symbols -->
        <symbol name="SS" place="head"/>
        <symbol name="SS" place="intext"/>
        
        <!-- Marks -->
        <mark name="quotation_mark" method="pen" place="intext" language="IT" text="buona"/>
        <mark name="plus_sign" method="pen" place="intext" language="IT" text="simplicit&agrave;"/>
        <mark name="quotation_mark" method="pen" place="intext"/>
        <mark name="plus_sign" method="pen" place="intext" language="IT" text="Pronto."/>
        <mark name="dot" method="pen" place="intext"/> <!--Dio ma-->
        <mark name="dot" method="pen" place="intext"/> <!--Chiede &-->
		<mark name="vertical_bar" method="pen" place="intext"/> <!--after finestra-->
		<mark name="vertical_bar" method="pen" place="intext"/> <!--after buttera-->
        <mark name="dot" method="pen" place="intext"/> <!--Giudeo-->
        <mark name="dot" method="pen" place="intext"/> <!--tocchi-->
        <mark name="dot" method="pen" place="intext"/> <!--buttera, come-->
        <mark name="bracket" method="pen" place="left_margin"/>
        <mark name="bracket" method="pen" place="left_margin"/>
        <mark name="bracket" method="pen" place="left_margin"/>
        <mark name="bracket" method="pen" place="left_margin"/>
        <mark name="plus_sign" method="pen" place="right_margin"/>
        <mark name="straight_quotation_mark" method="pen" place="right_margin"/> <!--far-->
		<mark name="apostrophe" method="pen" place="intext"/> <!--buttera, come-->
		<mark name="comma" method="pen" place="intext"/> <!--ducati gli-->
         
    </annotation>
</transcription>

