<?xml version="1.0" standalone="yes" ?>

<!DOCTYPE transcription [
<!ELEMENT transcription (page, annotation)>
<!ELEMENT page EMPTY>
	<!ATTLIST page filename CDATA #REQUIRED>
	<!ATTLIST page pagination CDATA #IMPLIED>
	<!ATTLIST page signature CDATA #IMPLIED>
	<!ATTLIST page reader CDATA #REQUIRED>
	
<!ELEMENT annotation (marginalia*, underline*, symbol*, mark*)>	
	<!ELEMENT marginalia (language*, translation?)>
	<!ATTLIST marginalia hand (English_secretary|Italian) #REQUIRED>
	<!ATTLIST marginalia date CDATA #IMPLIED>
	<!ATTLIST marginalia other_reader CDATA #IMPLIED>
	<!ATTLIST marginalia topic (Law|Astronomy|Warfare|Rhetoric) #IMPLIED> 
	<!ATTLIST marginalia anchor_text CDATA #IMPLIED>
	 	<!ELEMENT language (position*)>
			<!ATTLIST language ident (EN|EL|FR|IT|LA|ES) #REQUIRED> 
				<!ELEMENT position (marginalia_text*, person*, book*, location*, X-ref*, emphasis*)>
					<!ATTLIST position place (head|tail|left_margin|right_margin|intext) #REQUIRED>
					<!ATTLIST position book_orientation	(0|90|180|270) #REQUIRED>
						<!ELEMENT marginalia_text (#PCDATA)>
						<!ELEMENT person EMPTY>
							<!ATTLIST person name CDATA #REQUIRED>
						<!ELEMENT book EMPTY>
							<!ATTLIST book title CDATA #REQUIRED>
						<!ELEMENT location EMPTY>
							<!ATTLIST location name CDATA #REQUIRED>
						<!ELEMENT X-ref EMPTY>
							<!ATTLIST X-ref person CDATA #REQUIRED>
							<!ATTLIST X-ref book_title CDATA #REQUIRED>
						<!ELEMENT emphasis EMPTY> 
							<!ATTLIST emphasis method (chalk|pen) #REQUIRED>
							<!ATTLIST emphasis text CDATA #IMPLIED>
		<!ELEMENT translation (#PCDATA)>
	<!ELEMENT underline EMPTY>
		<!ATTLIST underline method (chalk|pen) #REQUIRED>
		<!ATTLIST underline type (straight|curved) #REQUIRED>
		<!ATTLIST underline language (EN|EL|FR|IT|LA|ES) #IMPLIED>
		<!ATTLIST underline text CDATA #IMPLIED> 
	<!ELEMENT symbol EMPTY>
		<!ATTLIST symbol name (Asterisk|Bisected_circle|Crown|Crescent|JC|HT|LL|Mars|Mercury|Opposite_planets|Square|SS|Sun) #REQUIRED>
		<!ATTLIST symbol place (head|tail|left_margin|right_margin|intext) #REQUIRED>
		<!ATTLIST symbol language (EN|EL|FR|IT|LA|ES) #IMPLIED>
		<!ATTLIST symbol text CDATA #IMPLIED>
	<!ELEMENT mark EMPTY>
		<!ATTLIST mark name	(apostrophe|box|bracket|circumflex|comma|dash|dot|equal_sign|hash|horizontal_bar|plus_sign|quotation_mark|semicolon|straight_quotation_mark|tilde|triple_dash|vertical_bar|X_sign) #REQUIRED>
		<!ATTLIST mark method (chalk|pen) #REQUIRED>
		<!ATTLIST mark place (head|tail|left_margin|right_margin|intext) #REQUIRED>
		<!ATTLIST mark language (EN|EL|FR|IT|LA|ES) #IMPLIED>
		<!ATTLIST mark text CDATA #IMPLIED>
			
<!ENTITY agrave "à">
<!ENTITY aacute "á">
<!ENTITY atiled "ã">
<!ENTITY eacute "é">
<!ENTITY egrave "è">
<!ENTITY ecirc "ê">
<!ENTITY ograve "ò">
<!ENTITY ocirc "Ô">
<!ENTITY euml "ë">
<!ENTITY igrave "ì">
<!ENTITY ugrave "ù">
]
>

<transcription>
    <page filename="Ha2.006v.tif" pagination="332" reader="Harvey"/>	<!-- ABO 11left -->
    <annotation>
        
        <!-- Marginalia -->
        <marginalia hand="Italian">
            <language ident="EN">
                <position place="head" book_orientation="0">
                    <marginalia_text>
                      Chrysotechnus never vnprouided, or vnperfe[t]: 
                    </marginalia_text>
                	<person name="Chrysotechnus"/>
                </position>
            	<position place="left_margin" book_orientation="0">
            		<marginalia_text>
            			but euer praesenting 
            		</marginalia_text>
            	</position>
            	<position place="intext" book_orientation="0">
            		<marginalia_text>
            			in witt, toung, &amp; execution. Allwais the
            		</marginalia_text>
            	</position>
            	<position place="left_margin" book_orientation="0">
            		<marginalia_text>
            			best actor, at words, or deeds.
            		</marginalia_text>
            		<emphasis method="chalk"/>
            	</position>
            </language>
        </marginalia>
    	<marginalia hand="Italian">
        	<language ident="LA">
        		<position place="left_margin" book_orientation="0">
        			<marginalia_text>
        			Quicq[ui]d in Deo, Deus quicq[ui]d in viro, vir.
        			Quicq[ui]d in opt[im]o optimum: in max[im]o ( maximu[m].
        			Abu[n]de est hominum ( bullarum:
        			</marginalia_text>
        			<emphasis method="chalk"/>
        		</position>
        		<position place="tail" book_orientation="0">
        			<marginalia_text>
        				homo palma, miraculum.
        			</marginalia_text>
        		</position>
        	</language>
        </marginalia>
    	<marginalia hand="Italian">
    		<language ident="LA">
    			<position place="intext" book_orientation="0">
    				<marginalia_text>
    					Cautela abundans non nocet.
    				</marginalia_text>
    			</position>
    		</language>
    	</marginalia>
    	<marginalia hand="Italian">
    		<language ident="LA">
    			<position place="intext" book_orientation="0">
    				<marginalia_text>
    					( Sera, sed seria nemesis. in perfidu[m] depositarium.
    				</marginalia_text>
    			</position>
    		</language>
    	</marginalia>
    	<marginalia hand="Italian">
    		<language ident="IT">
    			<position place="intext" book_orientation="0">
    				<marginalia_text>
    					ridicolo.
    				</marginalia_text>
    			</position>
    		</language>
    	</marginalia>
    	<marginalia hand="Italian">
    		<language ident="EN">
    			<position place="intext" book_orientation="0">
    				<marginalia_text>
    					) More in hart, then in face, or tounge.
    				</marginalia_text>
    				<emphasis method="chalk"/>
    			</position>
    		</language>
    	</marginalia>
    	<marginalia hand="Italian">
    		<language ident="LA">
    			<position place="tail" book_orientation="0">
    				<marginalia_text>
    					Occulta proprietas Aesopi, et
    					nonnullorum deformium.
    				</marginalia_text>
    				<person name="Aesop"/>
    			</position>
    		</language>
    	</marginalia>
    	<marginalia hand="Italian">
    		<language ident="LA">
    			<position place="left_margin" book_orientation="90">
    				<marginalia_text>
    					Vulgaris est, qui loquitur, aut exequitur, vt vulgaris.
    					Extraordinariu[m] viru[m] decet oratio, actioq[ue] extraordinaria: 
    				</marginalia_text>
    				<emphasis method="chalk"/>
    			</position>
    		</language>
    	</marginalia>
    	<marginalia hand="Italian">
    		<language ident="LA">
    			<position place="tail" book_orientation="90">
    				<marginalia_text>
    					singulare[m] vtraq[ue] singularis. 
    				</marginalia_text>
    				<emphasis method="pen"/>
    			</position>
    		</language>
    	</marginalia>
    	<marginalia hand="Italian">
    		<language ident="LA">
    			<position place="right_margin" book_orientation="270">
    				<marginalia_text>
    					Malo pygmaeum sophum, quam Gigantem Equu[m] cacotam: 
    					et plures quam aestimo ferreu[m] aureu[m] asinu[m]. 
    				</marginalia_text>
    			</position>
    		</language>
    	</marginalia>
        
        <!-- Underlines -->
        
        <underline method="pen" type="straight" language="IT" text="garzoni del Bancho"/>
    	<underline method="pen" type="straight" language="IT" text="habbiate gli occhi a Nicolao"/>
    	<underline method="pen" type="straight" language="IT" text="denari in deposito"/>
    	<underline method="pen" type="straight" language="IT" text="fatto fede di"/>
    	<underline method="pen" type="straight" language="IT" text="glie li neg&ograve;"/>
    	<underline method="pen" type="straight" language="IT" text="accusollo per falsario in"/>
    	<underline method="pen" type="straight" language="IT" text="fu morto"/>
    	<underline method="pen" type="straight" language="IT" text="questo gran tradimento"/>
    	<underline method="pen" type="straight" language="IT" text="che Dio ci sia, se io non ueggo uendetta"/>
    	<underline method="pen" type="straight" language="IT" text="confinato"/>
    	<underline method="pen" type="straight" language="IT" text="publicati i suoi beni"/>
    	<underline method="pen" type="straight" language="IT" text="capitare"/>
    	<underline method="pen" type="straight" language="IT" text="Iddio, tu c'eri"/>
    	<underline method="pen" type="straight" language="IT" text="cominci&ograve; a credere"/>
    	<underline method="pen" type="straight" language="IT" text="La uendetta di Dio non piomba in fretta"/>
    	<underline method="pen" type="straight" language="IT" text="haueua uenduti poderi"/>
    	<underline method="pen" type="straight" language="IT" text="case"/>
    	<underline method="pen" type="straight" language="IT" text="tuoi poderi"/>
    	<underline method="pen" type="straight" language="IT" text="bella uigna"/>
    	<underline method="pen" type="straight" language="IT" text="uenduta"/>
    	<underline method="pen" type="straight" language="IT" text="ella era torta, &amp;"/>
    	<underline method="pen" type="straight" language="IT" text="sarebbe infradiciata"/>
    	<underline method="pen" type="straight" language="IT" text="ui pioueua"/>
    	<underline method="pen" type="straight" language="IT" text="Magra scusa"/>
    	<underline method="pen" type="straight" language="IT" text="uende la casa"/>
    	<underline method="pen" type="straight" language="IT" text="ella temeua il fumo"/>
    	<underline method="pen" type="straight" language="IT" text="di prouerbio"/>
    	<underline method="pen" type="straight" language="IT" text="del Duca di Milano"/>
    	<underline method="pen" type="straight" language="IT" text="nero, &amp; brutto"/>
    	<underline method="pen" type="straight" language="IT" text="marauigliarsi"/>
    	<underline method="pen" type="straight" language="IT" text="padrone lo tenesse"/>
    	<underline method="pen" type="straight" language="IT" text="gi&agrave; qualche virt&ugrave; secreta"/>
    	<underline method="pen" type="straight" language="IT" text="ogniuno &egrave; buono"/>
    	<underline method="pen" type="straight" language="IT" text="qualche cosa"/>    
        
        <!-- Symbols: Asterisk|Bisected_circle|Crown|Crescent|JC|HT|LL|Mars|Mercury|Opposite_planets|Square|SS|Sun -->
        
        <symbol name="JC" place="intext"/>
    	<symbol name="JC" place="intext"/>
        
    	<!-- Marks: apostrophe|box|bracket|circumflex|comma|dash|dot|equal_sign|hash|horizontal_bar|plus_sign|quotation_mark|semicolon|tilde|triple_dash|vertical_bar|X_sign -->
    	<!-- Right margin -->
    	<mark name="dash" method="pen" place="right_margin"/> <!-- ha -->
    	<mark name="comma" method="pen" place="right_margin"/> <!-- ricchiedeua -->
    	<mark name="dash" method="pen" place="right_margin"/> <!-- mor -->
    	<mark name="dash" method="pen" place="right_margin"/> <!-- confina -->
    	<mark name="quotation_mark" method="pen" place="right_margin"/> <!-- Ma -->
    	<mark name="dash" method="pen" place="right_margin"/> <!-- Ma -->
    	<mark name="dash" method="pen" place="right_margin"/> <!-- il qua -->
    	<mark name="dash" method="pen" place="right_margin"/> <!-- buo -->
    	
    	<!-- Left margin -->
    	<mark name="equal_sign" method="pen" place="left_margin" /> <!-- uenduta -->
    	<mark name="quotation_mark" method="pen" place="left_margin" /> <!-- il quale -->
    	
    	<!-- Intext -->
    	<mark name="plus_sign" method="pen" place="intext"/> <!-- Nicolai -->
    	<mark name="dot" method="pen" place="intext"/> <!-- mano, uenendo -->
    	<mark name="dot" method="pen" place="intext"/> <!-- nego, e -->
    	<mark name="plus_sign" method="pen" place="intext"/> <!-- per falsario -->
    	<mark name="equal_sign" method="pen" place="intext"/> <!-- fu mor -->
    	<mark name="dot" method="pen" place="intext"/> <!-- sensale, il -->
    	<mark name="plus_sign" method="pen" place="intext"/> <!-- gran tradimento -->
    	<mark name="comma" method="pen" place="intext"/> <!-- se io non uoglio -->
    	<mark name="dot" method="pen" place="intext"/> <!-- capitare, disse -->
    	<mark name="comma" method="pen" place="intext"/> <!-- fretta dice il Poeta -->
    	<mark name="equal_sign" method="pen" place="intext"/> <!-- ui pioueua -->
    	<mark name="comma" method="pen" place="intext"/> <!-- pioueua come -->
    	<mark name="dot" method="pen" place="intext"/> <!-- scusa, & simile -->
    	<mark name="equal_sign" method="pen" place="intext"/> <!-- fumo -->
    	<mark name="quotation_mark" method="pen" place="intext"/> <!-- fumo.] -->
    	<mark name="plus_sign" method="pen" place="intext" language="IT" text="secreta"/> 
    	<mark name="quotation_mark" method="pen" place="intext"/> <!-- cosa.] -->
    	
    	<mark name="quotation_mark" method="pen" place="tail" language="LA" text="singulare[m]"/>
    	
    	
 
    </annotation>
</transcription>
