<?xml version="1.0" standalone="yes" ?>

<!-- Updated 10/10/2014 -->

<!DOCTYPE transcription [
<!ELEMENT transcription (page, annotation)>
<!ELEMENT page EMPTY>
	<!ATTLIST page filename CDATA #REQUIRED>
	<!ATTLIST page pagination CDATA #IMPLIED>
	<!ATTLIST page signature CDATA #IMPLIED>
	<!ATTLIST page reader CDATA #REQUIRED>
	
<!ELEMENT annotation (marginalia*, underline*, symbol*, mark*)>	
	<!ELEMENT marginalia (language*, translation?)>
	<!ATTLIST marginalia hand (English_secretary|Italian) #REQUIRED>
	<!ATTLIST marginalia date CDATA #IMPLIED>
	<!ATTLIST marginalia other_reader CDATA #IMPLIED>
	<!ATTLIST marginalia topic (Law|Astronomy|Warfare|Rhetoric) #IMPLIED> 
	<!ATTLIST marginalia anchor_text CDATA #IMPLIED>
	 	<!ELEMENT language (position*)>
			<!ATTLIST language ident (EN|EL|FR|IT|LA|ES) #REQUIRED> 
				<!ELEMENT position (marginalia_text*, person*, book*, location*, X-ref*, emphasis*)>
					<!ATTLIST position place (head|tail|left_margin|right_margin|intext|full_page) #REQUIRED>
					<!ATTLIST position book_orientation	(0|90|180|270) #REQUIRED>
						<!ELEMENT marginalia_text (#PCDATA)>
						<!ELEMENT person EMPTY>
							<!ATTLIST person name CDATA #REQUIRED>
						<!ELEMENT book EMPTY>
							<!ATTLIST book title CDATA #REQUIRED>
						<!ELEMENT location EMPTY>
							<!ATTLIST location name CDATA #REQUIRED>
						<!ELEMENT X-ref EMPTY>
							<!ATTLIST X-ref person CDATA #REQUIRED>
							<!ATTLIST X-ref book_title CDATA #REQUIRED>
						<!ELEMENT emphasis EMPTY> 
							<!ATTLIST emphasis method (chalk|pen) #REQUIRED>
							<!ATTLIST emphasis text CDATA #IMPLIED>
		<!ELEMENT translation (#PCDATA)>
	<!ELEMENT underline EMPTY>
		<!ATTLIST underline method (chalk|pen) #REQUIRED>
		<!ATTLIST underline type (straight|curved) #REQUIRED>
		<!ATTLIST underline language (EN|EL|FR|IT|LA|ES) #IMPLIED>
		<!ATTLIST underline text CDATA #IMPLIED> 
	<!ELEMENT symbol EMPTY>
		<!ATTLIST symbol name (Asterisk|Bisected_circle|Crown|Crescent|JC|HT|LL|Mars|Mercury|Opposite_planets|Square|SS|Sun) #REQUIRED>
		<!ATTLIST symbol place (head|tail|left_margin|right_margin|intext) #REQUIRED>
		<!ATTLIST symbol language (EN|EL|FR|IT|LA|ES) #IMPLIED>
		<!ATTLIST symbol text CDATA #IMPLIED>
	<!ELEMENT mark EMPTY>
		<!ATTLIST mark name	(apostrophe|box|bracket|circumflex|comma|dash|dot|equal_sign|hash|horizontal_bar|plus_sign|quotation_mark|semicolon|straight_quotation_mark|tilde|triple_dash|vertical_bar|X_sign) #REQUIRED>
		<!ATTLIST mark method (chalk|pen) #REQUIRED>
		<!ATTLIST mark place (head|tail|left_margin|right_margin|intext) #REQUIRED>
		<!ATTLIST mark language (EN|EL|FR|IT|LA|ES) #IMPLIED>
		<!ATTLIST mark text CDATA #IMPLIED>
			
			
<!ENTITY agrave "à">
<!ENTITY aacute "á">
<!ENTITY atiled "ã">
<!ENTITY eacute "é">
<!ENTITY egrave "è">
<!ENTITY ecirc "ê">
<!ENTITY ograve "ò">
<!ENTITY ocirc "Ô">
<!ENTITY euml "ë">
<!ENTITY igrave "ì">
<!ENTITY ugrave "ù">
]
>

<transcription>

	<page filename="Ha2.013r" pagination="345" reader="Harvey"/>	<!-- ABO 17right -->
    	<annotation>
    		
            		<!-- Marginalia -->
    		
        		<marginalia hand="Italian">
        			<language ident="LA">
            			               <position place="head" book_orientation="0">
                    				<marginalia_text>
                    					Animus, imperator Corporis, et fortunae.
                    				</marginalia_text>
            			               	<emphasis method="chalk"/>
            			               </position>
        			</language>
        		</marginalia>
    		<marginalia hand="Italian">
    			<language ident="IT">
    				<position place="intext" book_orientation="0">
    					<marginalia_text>
    						Giulio 3. padrone del diuino Pietro Aretino.
    					</marginalia_text>
    					<person name="Pope Julius III"/>
    					<person name="Pietro Aretino"/>
    				</position>
    			</language>
    		</marginalia>
    		<marginalia hand="Italian">
    			<language ident="IT">
    				<position place="intext" book_orientation="0">
    					<marginalia_text>
    						humore del mondo.
    					</marginalia_text>
    				</position>
    			</language>
    		</marginalia>
    		<marginalia hand="Italian">
    			<language ident="LA">
    				<position place="intext" book_orientation="0">
    					<marginalia_text>
    						) { Animus facit magnum: Fortuna, magnatem.
    					</marginalia_text>
    					<emphasis method="chalk"/>
    				</position>
    			</language>
    		</marginalia>
    		<marginalia hand="Italian">
    			<language ident="IT">
    				<position place="intext" book_orientation="0">
    					<marginalia_text>
    						ridicolo.
    					</marginalia_text>
    				</position>
    			</language>
    			<language ident="LA">
    				<position place="intext" book_orientation="0">
    					<marginalia_text>
    						Sic transit gloria mundi.
    					</marginalia_text>
    				</position>
    			</language>
    		</marginalia>
    		<marginalia hand="Italian">
    			<language ident="LA">
    				<position place="intext" book_orientation="0">
    					<marginalia_text>
    						Prudentia, theoria; fortitudo Praxis.
    					</marginalia_text>
    				</position>
    			</language>
    		</marginalia>
    		<marginalia hand="Italian">
    			<language ident="LA">
    				<position place="tail" book_orientation="0">
    					<marginalia_text>
    						Fortuna, fortitudo vna.
    					</marginalia_text>
    					<emphasis method="chalk"/>
    				</position>
    			</language>
    		</marginalia>
    		
    		<marginalia hand="Italian">
    			<language ident="LA">
    				<position place="left_margin" book_orientation="90">
    					<marginalia_text>
    						Animus est, qui facit foelicem, aut miserum.
    					</marginalia_text>
    				</position>
    			</language>
    		</marginalia>
        
    		<marginalia hand="Italian">
    			<language ident="LA">
    				<position place="right_margin" book_orientation="270">
    					<marginalia_text>
    						Vilis animus est, qui non dominatur corpori. Magnus animus, ide[o]q[ue]	<!-- I don't quite understand why there's an acute accent above "ideoque." -->
    						tranquilius illud, tam Corpori imperat, qu&agrave;m fortunae aegru[m]; quantumcunq[ue] aut haec aut afflict[a].	<!-- The position of various elements in this sentence is strange, should I record certain words as "intext"? -->
    					</marginalia_text>
    					<emphasis method="chalk"/>
    				</position>
    			</language>
    		</marginalia>
        
	    	<!-- Underlines -->
	        
	    	<underline method="pen" type="straight" text="scarpe Pontificali"/>
    		<underline method="pen" type="straight" text="giudicandole strette"/>
    		<underline method="pen" type="straight" text="non fu mai scarpa, che mi calzasse meglio"/>
    		<underline method="pen" type="straight" text="giovani"/>
    		<underline method="pen" type="straight" text="amici miei"/>
    		<underline method="pen" type="straight" text="sul canto"/>
    		<underline method="pen" type="straight" text="Zoppo da amendue"/>
    		<underline method="pen" type="straight" text="caminaua forte a piu"/>
    		<underline method="pen" type="straight" text="hor con l'una, &amp; hora con"/>
    		<underline method="pen" type="straight" text="spalla battesse"/>
    		<underline method="pen" type="straight" text="co[m]pagni il piu faceto"/>
    		<underline method="pen" type="straight" text="quello"/>
    		<underline method="pen" type="straight" text="che festa &egrave; domani"/>
    		<underline method="pen" type="straight" text="cura di feste"/>
    		<underline method="pen" type="straight" text="uoi sonate cosi forte a doppio"/>
    		<underline method="pen" type="straight" text="difetti naturali non"/>
    		<underline method="pen" type="straight" text="scherzo"/>
    		<underline method="pen" type="straight" text="tosto compassione"/>
    		<underline method="pen" type="straight" text="empio &egrave; chi"/>
    		<underline method="pen" type="straight" text="feste in Fiorenza"/>
    		<underline method="pen" type="straight" text="tessitor di lana"/>
    		<underline method="pen" type="straight" text="horreuolmente a gli spettacoli"/>
    		<underline method="pen" type="straight" text="moglie con"/>
    		<underline method="pen" type="straight" text="spendeua troppo, &amp; rimarrebbono poueri"/>
    		<underline method="pen" type="straight" text="che per farmi honore ti metterei in chiasso"/>
    		<underline method="pen" type="straight" text="Parola libera"/>
    		<underline method="pen" type="straight" text="semplicemente"/>
    		<underline method="pen" type="straight" text="una frotta di giouani"/>
    		<underline method="pen" type="straight" text="andauano pazzeggiando per"/>
    	
	       
	    	<!-- Symbols: Asterisk|Bisected_circle|Crown|Crescent|JC|HT|LL|Mars|Mercury|Opposite_planets|Square|SS|Sun -->
	        	
	        	<symbol name="SS" place="intext"/>
	      		
	    	<!-- Marks: apostrophe|box|bracket|circumflex|comma|dash|dot|equal_sign|hash|horizontal_bar|plus_sign|quotation_mark|semicolon|straight_quotation_mark|tilde|triple_dash|vertical_bar|X_sign -->
	    	
	    	<!-- Right margin -->
	    	<mark name="dash" method="pen" place="right_margin"/> <!-- Fioren -->
    		<mark name="dash" method="pen" place="right_margin"/> <!-- spal -->
    		<mark name="dash" method="pen" place="right_margin"/> <!-- pan -->
    		<mark name="dash" method="pen" place="right_margin"/> <!-- quel -->
    		<mark name="quotation_mark" method="pen" place="right_margin"/> <!-- feste -->
    		<mark name="comma" method="pen" place="right_margin"/> <!-- scherzo -->
    		<mark name="dash" method="pen" place="right_margin"/> <!-- co[n] -->
    		<mark name="quotation_mark" method="pen" place="right_margin"/> <!-- honore --> 
	    	
	    	<!-- Left margin -->
	    	<mark name="bracket" method="pen" place="left_margin"/> <!-- bene ... pa -->
    		<mark name="straight_quotation_mark" method="pen" place="left_margin"/> <!-- disse colui? -->
    		<mark name="straight_quotation_mark" method="pen" place="left_margin"/> <!-- ti metterei -->
		    
	    	<!-- Intext -->
	    	<mark name="dot" method="pen" place="intext"/> <!-- piede, disse: -->
    		<mark name="dot" method="pen" place="intext"/> <!-- following SS symbol -->

    </annotation>
</transcription>